if(EXISTS "/home/ahmed/tek/tek3/B-CPP-500-LYN-5-1-rtype-maxime.premont/docs/libs/Network/networkTests[1]_tests.cmake")
  include("/home/ahmed/tek/tek3/B-CPP-500-LYN-5-1-rtype-maxime.premont/docs/libs/Network/networkTests[1]_tests.cmake")
else()
  add_test(networkTests_NOT_BUILT networkTests_NOT_BUILT)
endif()
